[package]
name = "dbg64_plugins"
version = "0.1.0"
edition = "2021"
build="build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
autocxx-bindgen = "0.59.13"

[profile.release]
lto = "fat"
codegen-units = 1